# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Bazaar' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Bazaar

  target 'Bazaar-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BazaarTests' do
    inherit! :search_paths
    # Pods for testing
  end
 pod 'Google/SignIn'
 pod 'GTMOAuth2','~> 1.1'
end

target 'Bazaar-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Bazaar-tvOS

end
